version: "3.3"
services:
  postgres-service:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb-service:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongodata:/data/db
volumes:
  pgdata:
  mongodata: